#!/usr/bin/env sh
while read file
do
        case "$1" in
	"r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
	"x")
		convert "$file" -brightness-contrast 3x10 -unsharp 0x1 "$file" ;;
	"c")
		convert "$file" -deskew 40% -gravity Center -crop 97%x "$file" ;;
	"d")
		[ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
        esac
done
