[qt]
GUIEffects=none
KDE\contrast=4
KWinPalette\activeBackground=#c2defa
KWinPalette\activeBlend=#fcfcfc
KWinPalette\activeForeground=#000000
KWinPalette\activeTitleBtnBg=#eff0f1
KWinPalette\frame=#eff0f1
KWinPalette\inactiveBackground=#eff0f1
KWinPalette\inactiveBlend=#4b4743
KWinPalette\inactiveForeground=#bdc3c7
KWinPalette\inactiveFrame=#eff0f1
KWinPalette\inactiveTitleBtnBg=#eff0f1
Palette\active=#232627, #eff0f1, #ffffff, #f6f7f7, #888e93, #c4c8cc, #232627, #ffffff, #232627, #fcfcfc, #eff0f1, #474a4c, #c6e2fe, #000000, #00a3ec, #7f8c8d, #eff0f1, #000000, #232627, #fcfcfc, #7f8c8d, #c6e2fe
Palette\disabled=#a0a1a2, #e3e5e7, #ffffff, #ebedee, #82878c, #bbc0c5, #a8a9a9, #ffffff, #a0a1a2, #f0f0f0, #e3e5e7, #474a4c, #e3e5e7, #a0a1a2, #88d5f5, #c7cbcb, #e3e5e7, #000000, #232627, #fcfcfc, #c7cbcb, #e3e5e7
Palette\inactive=#232627, #eff0f1, #ffffff, #f6f7f7, #888e93, #c4c8cc, #232627, #ffffff, #232627, #fcfcfc, #eff0f1, #474a4c, #cbe4fe, #232627, #00a3ec, #7f8c8d, #eff0f1, #000000, #232627, #fcfcfc, #7f8c8d, #cbe4fe
font="Fira Sans,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"
