#!/bin/sh

try_run() {
  # local command="$1"
  $1 2>&1 | logger -t "xprofile:$1" & disown
}

[ -f ~/.Xresources ] && xrdb -merge -I$HOME ~/.Xresources

try_run "$(which VBoxClient-all)"
try_run "$(which setbg)"
try_run "$(which dunst)"
try_run "$(which picom)"
try_run "$(which gentoo-pipewire-launcher)"

try_run "xset r rate 300 50"
try_run "xinput disable 11" # NOTE: works best with IDs -- see xinput list
