#!/bin/sh

xrandr --dpi 96 # Set DPI. User may want to use a larger number for larger screens.
setbg &         # set the background with the `setbg` script
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup

autostart="VBoxClient-all picom dunst unclutter pipewire remapd"

for program in $autostart; do
  pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

xset r rate 300 50
# xinput disable 11
setxkbmap -option caps:swapescape
